# Generated by Django 3.2.12 on 2024-07-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_item_creater'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='product_item',
            name='attributes',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_category',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product_item',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
