# Generated by Django 3.2.12 on 2024-07-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_product_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_item_image',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
    ]
