# Generated by Django 3.2.12 on 2024-08-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_product_item_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='default.jpeg', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product_category',
            name='cover_image',
            field=models.ImageField(default='default.jpeg', upload_to='product_category/'),
        ),
        migrations.AlterField(
            model_name='product_item_image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='production.product_item'),
        ),
    ]
