# Generated by Django 3.2.12 on 2024-08-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_auto_20240802_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_length',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_weight',
        ),
        migrations.RemoveField(
            model_name='product',
            name='default_width',
        ),
        migrations.AlterField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default='products/default.jpeg', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='cover_image',
            field=models.ImageField(default='products/default.jpeg', upload_to='product_category/'),
        ),
    ]
