# Generated by Django 3.2.12 on 2024-07-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_packaging', '0002_auto_20240731_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package_s2i',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package_s2i',
            name='send_by',
            field=models.DateField(blank=True, null=True),
        ),
    ]
